### ISSUE TITLE
遗物：静籁永恒

### ISSUE THREAD

**Issue by ExtraMeteorP** [ExtraMeteorP/ExtraBotany#7]
获得方式：**共鸣屋**内8个**共鸣碎片**兑换获得
分2个模式:**静籁**和**永恒**
静籁模式：对玩家中心半径7*7生效，灭火、除雪(片)
冻结玩家脚下的水，凝固脚下的岩浆

永恒模式：包内每tick产100mana魔力，最大储量5w
不可放在魔力池上输出魔力，否则爆炸

PS:
共鸣屋WIP，内有3个交易槽，每3个MC天随机刷新为新的3个交易项目
1个D20开出的遗物可以拆解为1个共鸣碎片

**Comment by zqr95518** [comment]
我的天，这个每tick回蓝太丧病了，顶多每秒不然卡死，最好还能关掉
